Repository konveyor/move2kube-api, pull requests merged in 2020-12, with the labels that each got.

#45 fix: refactor the release workflow to match the cli release workflow
  .github/workflows/assignproject.yml
  .github/workflows/release.yml
  .github/workflows/tag.yml
  .grenrc.js
Labels: bug

#46 fix: remove creation and uploading of release assets
  .github/workflows/assignproject.yml
  .github/workflows/build.yml
  .github/workflows/prbuild.yml
  .github/workflows/release.yml
Labels: bug

#47 fix: reformat cli change workflow
  .github/workflows/clichange.yml
Labels: bug

#49 feat: label pull requests based on their title
  .github/workflows/clichange.yml
  .github/workflows/labelpr.yml
  .github/workflows/prbuild.yml
Labels: enhancement

#52 ci: clean up workflows to work together across multiple repos
  .github/workflows/build.yml
  .github/workflows/clichange.yml
  .github/workflows/labelpr.yml
  .github/workflows/prbuild.yml
  .github/workflows/release.yml
  .github/workflows/tag.yml
  .grenrc.js
  Dockerfile
  Makefile
Labels: ci

#53 feat: Parameterize port and add verbose option to command line
  Dockerfile
  Makefile
  cmd/move2kubeapi/move2kubeapi.go
  docker-compose.yml
  go.mod
  go.sum
  internal/application/IApplication.go
  internal/move2kubeapi/move2kubeapi.go
Labels: feat

#54 ci: add workflow_dispatch so build can be triggered from the move2kube repo
  .github/workflows/build.yml
Labels: ci

#55 ci: Add support for all-in-one image build
  .github/workflows/build.yml
  .github/workflows/release.yml
Labels: ci

#56 feat: Use fedora as base image
  Dockerfile
Labels: feat

#60 ci: fix bug where the 2 args were being treated as a single arg and passed to GREN
  .github/workflows/release.yml
Labels: ci

#61 ci: see https://github.com/konveyor/move2kube/pull/371 for details
  .github/workflows/release.yml
Labels: ci
