Repository konveyor/move2kube-api, pull requests merged in 2021-02, with the labels that each got.

#70 feat: compress binaries
  .github/workflows/build.yml
  .github/workflows/prbuild.yml
  .github/workflows/release.yml
  Dockerfile
  Makefile
Labels: feat

#71 fix: replace gren with custom action because gren doesn't handle previous tag properly
  .github/workflows/release.yml
  .grenrc.js
Labels: fix

#72 chore: previous tag is required to calculate changelog
  .github/workflows/release.yml
Labels: chore

#73 chore: Move to go 1.16
  Dockerfile
  go.mod
  go.sum
Labels: chore
