Repository konveyor/move2kube-api, pull requests merged in 2024-07, with the labels that each got.

#166 feat: add query parameters to dump CLI log file into stdout
  assets/openapi.json
  internal/filesystem/filesystem.go
  internal/filesystem/interface.go
  internal/move2kubeapi/handlers/handlers.go
  internal/move2kubeapi/handlers/outputs.go
  internal/move2kubeapi/handlers/plan.go
Labels: feat

#165 fix: respect DOCKER_HOST env var for better container runtime Support
  internal/filesystem/filesystem.go
Labels: fix

#167 ci: fix the HTTP 404 status error
  .github/workflows/release.yml
Labels: ci
